### ISSUE TITLE
create API documentation

### ISSUE THREAD

**Issue by imballinst** [imballinst/count-up-down#1]
At the moment, we only have 2 functions, but perhaps it would be a good idea to include it in the main README, particularly so that if users want to know what functions are exposed in the browser and in Node.js environment.

## Tasks

- [x] Find out a decent TSDoc doc generation (probably output it as Markdown or something)
- [x] Generate the markdowns
- [x] Link the markdowns from the main README
- [x] **[Optional]** Add GitHub actions to verify?

**Comment by imballinst** [comment]
I ended up with https://github.com/TypeStrong/typedoc. I think it's a very good tool (or maybe I'm just lazy to find its alternatives). I generated them all as Markdown, so it's still within the context of GitHub. Would a dedicated site be necessary? I'm not sure, maybe. But not now.

I have installed the `typedoc` package, alongside `typedoc-plugin-markdown` which is very good considering I want Markdown as an output instead of HTML. I use this script to clean and generate the static files:

```
"generate:doc": "rm -rf api/docs && typedoc --plugin typedoc-plugin-markdown --readme none --out api/docs src/node src/browser src/common/*.ts"
```

There are few adjustments regarding the file structure, because flat file structure doesn't really make sense for the output. I grouped them up by `common`, `node`, and `browser`. I'll write more in the PR.
